### PR TITLE
Add 'wait' subcommand

### PR DESCRIPTION
**Pull request by stephank**
This adds a `wait` subcommand to wait until the queue is idle. In addition, I've added a `--tag` option to both `queue` and `wait` so it's possible to wait on a specific set of jobs by tag.

This is useful to synchronize processes. For example, we have a build machine that uploads to a private cache, and once the build is complete, another machine is instructed to download from this cache. This allows us to wait for the queue to finish right before we send that instruction.

### CODE REVIEW

**Comment by stephank** [comment]
I've also added a `-concurrency` option. The default, 0, means infinite and so has the same behaviour as before. But I had a need for running jobs in order, so I use `-concurrency 1`. Higher values also work fine, and could be useful.

The buffer size for the `workerRequests` channel (256) is a little arbitrary. I chose a decently large number, and assumed the backing for it would just be a pointer array, so effectively 2 KiB on 64-bit architectures. But I'm not sure if that's true. If exceeded, connections will hang. (Doesn't apply to the 'infinite concurrency' case.)

**Comment by adisbladis** [comment]
Wow! I didn't expect anyone outside of https://github.com/nix-community/infra was actually using this!

> But I'm not sure if that's true. If exceeded, connections may hang. (Didn't really test what happens. Doesn't apply to the 'infinite concurrency' case.)

They should just block until the channel has ample buffer space.

**Comment by adisbladis** [comment]
If more people are using this we should consider adding it to nixpkgs.

**Comment by stephank** [comment]
We're using flakes and have this pinned to a commit, so interface changes are not a problem for us. 🙂

We're only just starting to use it. We were previously just doing `nix copy` at the end of a NixOS build, but that didn't cache build dependencies, hence the need for a post-build-hook instead. (Plus the async nature can save some time.)

I'm not sure how this is used in your infra, but doing concurrent uploads from the queue like that turned out to be a bit of trouble at first. Different uploads would quickly overlap during a bigger build, causing lots of duplicate work and CPU churn from xz compression. The duplicate work is a side-effect of `nix copy` traversing dependencies, which often contains stuff pulled from cache.nixos.org as part of the build. Perhaps that's not the case for your infra?

I also tried `nix copy --no-recursive`, but that in general seems to not work, causing 'invalid reference' errors for stuff that was pulled from cache.nixos.org and never added to our own binary cache. Plus, I prefer mirroring the parts of cache.nixos.org that we use. (Though I think even this solution may miss some build dependencies.)

But everything seems peachy now with `--concurrency 1`. 👍

**Comment by adisbladis** [comment]
> I'm not sure how this is used in your infra, but doing concurrent uploads from the queue like that turned out to be a bit of trouble at first. Different uploads would quickly overlap during a bigger build, causing lots of duplicate work and CPU churn from xz compression. The duplicate work is a side-effect of nix copy traversing dependencies, which often contains stuff pulled from cache.nixos.org as part of the build. Perhaps that's not the case for your infra?

On the nix-community infra we use the cachix client which may have some smarts that `nix copy` doesn't. I don't know but we haven't experienced the same thing.

> I also tried nix copy --no-recursive, but that in general seems to not work, causing 'invalid reference' errors for stuff that was pulled from cache.nixos.org and never added to our own binary cache. Plus, I prefer mirroring the parts of cache.nixos.org that we use. (Though I think even this solution may miss some build dependencies.)

Iirc `nix copy` implies realisation, so you are very likely missing build dependencies from your cache. If you're copying over ssh you can use the old `nix-copy-closure` command on a drv to copy over the entire build closure.

**Comment by stephank** [comment]
> Iirc nix copy implies realisation, so you are very likely missing build dependencies from your cache. If you're copying over ssh you can use the old nix-copy-closure command on a drv to copy over the entire build closure.

Realisation is harmless in our case, I think. It's definitely the missing dependencies it's copying. That's also fine, just not when it happens in parallel apparently.

But as for what's actually copied, I think `nix copy` and `nix-copy-closure` do the same? Both call `Store::computeFSClosure()` and `copyPaths()` roughly the same way. Some I'm not sure how I'd capture build dependencies that way.

Either way, we're using an S3 binary cache, so it doesn't look like we can use the old command. 🙂

**Pull request merged**
