### PR TITLE
test: add example that sign packages

### LINKED ISSUE #12: error: you are not privileged to add signatures when running `nix store sign` in postBuildScriptContent
related: https://github.com/NixOS/nix/issues/1708

I guess that would be solved by adding to `queued-build-hook` user  to `trusted-users`?

### PR DESCRIPTION
**Pull request by jfroche**
Improve post build script in test to shows how to sign a package.

Waiting for https://github.com/NixOS/nix/pull/8589 to be merged.

closes #12

### CODE REVIEW

**Comment by Mic92** [comment]
Do we still need to wait for a nix package update here?

**Comment by jfroche** [comment]
Change in nix has been merged and release. This is good to merge.

**Comment by Mic92** [comment]
@mergify queue

**Comment by Mic92** [comment]
@mergify requeue

**Comment by Mic92** [comment]
@mergify queue

**Pull request merged**
